#!/usr/bin/env bash

set -euo pipefail

Start Citadel
if [[ $UID -ne 0 ]]; then
echo "Citadel must be started as root"
echo "Please re-run this script as"
echo " sudo $0"
exit 1
fi

Check dependencies
for cmd in readlink dirname ip docker rsync jq curl; do
command -v "$cmd" >/dev/null 2>&1 || {
echo >&2 "This script requires "$cmd" to be installed"
exit 1
}
done

CITADEL_ROOT="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.."
CITADEL_LOGS="${CITADEL_ROOT}/logs"

if [[ ! -d "$CITADEL_ROOT" ]]; then
echo "Root dir does not exist '$CITADEL_ROOT'"
exit 1
fi

Configure Citadel if it isn't already configured
if [[ ! -f "${CITADEL_ROOT}/statuses/configured" ]]; then
CADDY_PORT=${CADDY_PORT:-80} CADDY_HTTPS_PORT=${CADDY_HTTPS_PORT:-443} NETWORK="${NETWORK:-mainnet}" "${CITADEL_ROOT}/scripts/configure"
fi

echo
echo "======================================"
echo "============= STARTING ==============="
echo "============= CITADEL ================"
echo "======================================"
echo

echo "Setting environment variables..."
echo

Check Citadel OS
[[ -f "/etc/default/citadel" ]] && source "/etc/default/citadel"
IS_CITADEL_OS=${CITADEL_OS:-}
export IS_CITADEL_OS=${IS_CITADEL_OS:+true}

Whitelist device IP, hostname and hidden service for CORS
DEVICE_IP=$(hostname -I | awk '{print $1}') || DEVICE_IP="$(ip addr show $(ip route | awk '/default/ { print $5 }') | grep "inet" | head -n 1 | awk '/inet/ {print $2}' | cut -d'/' -f1)"
DEVICE_HOSTNAME="$(hostname)" || DEVICE_HOSTNAME="$(cat /etc/hostname)"
DEVICE_HOSTS="http://${DEVICE_IP},http://${DEVICE_HOSTNAME}.local,https://${DEVICE_HOSTNAME}.local,http://${DEVICE_HOSTNAME},https://${DEVICE_HOSTNAME}"
if [[ -f "${CITADEL_ROOT}/tor/data/web/hostname" ]]; then
hidden_service_url=$(cat "${CITADEL_ROOT}/tor/data/web/hostname")
DEVICE_HOSTS="${DEVICE_HOSTS},http://${hidden_service_url}"
fi
export DEVICE_HOSTS="$DEVICE_HOSTS"
export DEVICE_IP="$DEVICE_IP"
export DEVICE_HOSTNAME="${DEVICE_HOSTNAME}.local"
export DEVICE_IP="$DEVICE_IP"

Increase default Docker and Compose timeouts to 240s
as bitcoin can take a long while to respond
export DOCKER_CLIENT_TIMEOUT=240
export COMPOSE_HTTP_TIMEOUT=240

cd "$CITADEL_ROOT"

echo "Starting karen..."
echo
./karen &>> "${CITADEL_LOGS}/karen.log" &

echo "Starting status monitors..."
echo
